version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-first-aws-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17x174khbil5b"
s3_prefix = "my-first-aws-sam"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
